@url_dev=http://localhost:3052/v1/api/

### signup
POST {{url_dev}}/shop/signupeeee
Content-Type: application/json
x-api-key:392bcd408887fcc4e8a1ffdf08af087ba1c259024614aedaf737cb5e7c809ced667145d17c73f00d1af8f44819e0ecf852d8aca9cccd345d0b47b28106a778e0

{
    "name": "viethoang",
    "email": "viet.gs08@gmail.com",
    "password":"kiloma123"
}